### ISSUE TITLE
VC version 14.1

### ISSUE THREAD

**Issue by Jan-E** [winlibs/cURL#8]
@weltling
FYI, Curl now refers to VS2017 as VC 14.1:
https://github.com/curl/curl/commit/222de37f95bffca8d5378b020ea9db0e49ee4309

I did point the different practice in the PHP and Apache world:
https://github.com/curl/curl/pull/2189#issuecomment-372911208

**Comment by weltling** [comment]
Thanks for the ping. In VS it's now also renamed to `...\2017\Enterprise\VC\Redist\MSVC\14.13.26020\x64\Microsoft.VC141.CRT`, which is kinda confusing :/ Good to know anyway, that cURL has changed it, but it doesn't change the world. For PHP, it would be certainly a very confusing move, too. Many projects still hold on `vc15`, otherwise lets watch the next CRT version.

Thanks.
